#!/bin/bash

declare -A direnv_layout_dirs
direnv_layout_dir() {
    local hash dir
    echo "${direnv_layout_dirs[$PWD]:=$(
        hash="$(sha1sum - <<< "$PWD" | head -c40)"
        dir="$(basename "${PWD}")"
        echo "${XDG_CACHE_HOME:-${HOME}/.cache}/direnv/layouts/${dir}-${hash}"
    )}"
}
